### ISSUE TITLE
Equal sign (=) gets trimmed at the end of a header value

### ISSUE THREAD

**Issue by slaverman** [peak3d/inputstream.adaptive#145]
The license server authenticates a user by looking at a specific token in the request headers. This token always ends with an equal sign (=). See example below.
```
playitem.setProperty('inputstream.adaptive.license_key', 'license_url|username=test&token=abcde12345=|R{SSM}|')
```

I see in my logs that the equal sign is trimmed at the end of my token and probably is interpreted as a new header value for the Expect key. See example below.
```
DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Expect: '
DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'username : test'
DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'token: abcde12345'
```
Is there a way to include my equal sign at the end of my token in the header value? Thanks in advance :)

**Comment by JinRonin** [comment]
Not sure if it works, but you could try to url encode it.
https://stackoverflow.com/questions/5607551/how-to-urlencode-a-querystring-in-python/9345102#9345102

**Comment by slaverman** [comment]
@JinRonin That worked! Thanks :)

The next challenge is create the correct request payload, because I get a 400 HTTP error...

**Comment by peak3d** [comment]
Most probably the Content-Type Header

**Comment by slaverman** [comment]
` DEBUG: AddOnLog: InputStream Adaptive: License update successful`

I got the license. The next problem is now that I get a 404 after the header downloads. Apparently the mp4 files I'm looking for are not on found...

`09:28:20.753 T:12500   DEBUG: CurlFile::Open(0x275c92e8180)`
`09:28:20.875 T:12500   ERROR: CCurlFile::Open failed with code 404`
`doesn't provide any data: invalid`

**Comment by peak3d** [comment]
You have to figure out what headers are mandatory when fetching the mp4 streams.

You can use the inputstream.adaptive.stream_headers property to define Headers which are used for manifest and stream download

**Comment by slaverman** [comment]
When I make the same GET request without headers in Postman I also get a 404. But after 30 seconds or something I get a 200 with the mp4 file. Seems like a delay on the server side....

**Comment by peak3d** [comment]
You'll find out how it works, in most cases your behaviour is because of already used tokens which are gathered before stream start. Make sure that your session / tokens are valid if you start the stream.

There are also cases where a session / token is only valid for some seconds (and will be refreshed during playback). But if you follow what web site is doing you'll succeed

**Comment by slaverman** [comment]
It's weird that the URL (which gives the 404) I copied from the kodi.log works after 30 seconds in Postman...

**Comment by slaverman** [comment]
It looks like the number of the video has an offset or something. If I make a GET request for /video2/10131540.m4s it is not working instantly, but after ~30 seconds. So I tried to request /video2/10131530.m4s and that worked. /video2/10131535.m4s worked after ~15 seconds

**Comment by JinRonin** [comment]
Sounds like its trying to download chunks that do not exist yet.
Is it listed in the manifest?
Compare with Browser and check how its handled there.

**Comment by slaverman** [comment]
See https://pastebin.com/KsYhgwL1 for the manifest. I get a 404 for /video2/10134389.m4s

**Comment by JinRonin** [comment]
From my limited point of view this is due to presentationTimeOffset

see: https://github.com/Dash-Industry-Forum/dash.js/issues/74#issuecomment-25399032

**Comment by peak3d** [comment]
@JinRonin yes, I agree, unfortunately I have no media to reproduce.

**Comment by JinRonin** [comment]
try: http://dash.edgesuite.net/dash264/TestCases/5b/nomor/1.mpd
this yields in 404 when skipping too far

**Comment by slaverman** [comment]
Or try the Clear, live DASH example from Shaka Player, https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.mpd

Before I dive into the source code of this addon, is it possible to create my own segmentTimeline and pass this to the player?

**Comment by peak3d** [comment]
> Before I dive into the source code of this addon, is it possible to create my own segmentTimeline and pass this to the player?
Do I understand right that you prefer a hack instead a solution?

@JinRonin have you understood how to get this offset evaluated? From my current understanding I have to look into the media (m4s) first to get an timestamp for the selection.
I'm unable to figure out from mpd what the latest accessible segment is. Any ideas?

**Comment by slaverman** [comment]
> Do I understand right that you prefer a hack instead a solution?

I would not call it a hack. A temporary workaround would be a better choice of words.

A solution that supports all the aspects of the current DASH specs seems like a great amount of work. Letting users deal with gathering all the segmentsurl's and pass them to the player would give some time to work on a real solution.

**Comment by peak3d** [comment]
You'll not be able to create a woraround without knowing what you want to do - and at the time you know / have understood, implementation is simple (in general)

I pushed a commit, pls. try if it works for you

**Comment by slaverman** [comment]
> I pushed a commit, pls. try if it works for you
Did you also make a build by any chance? 😇 I'm don't have CMake on this machine....

**Comment by peak3d** [comment]
What OS ?

**Comment by slaverman** [comment]
Windows 10 x64

**Comment by peak3d** [comment]
If this build is finished: http://jenkins.kodi.tv/view/Windows/job/WIN-64/5159/ you should find the new package here: https://mirrors.kodi.tv/test-builds/windows/win64/

**Comment by slaverman** [comment]
Thanks! It plays for two minutes with the nightly build of 31-5 :) 

After two minutes it stops because the token in the request URL for the segments becomes invalid. What would you recommend; if the token expires request a whole new manifest ? Or is it possible to replace the token in the request URL's of the segments with another one?

**Comment by peak3d** [comment]
Yes, there is a parameter in inputstream.adaptive which tells inputstream.adaptive to request an URL for new license request. @JinRonin wil know best IIRC

**Comment by slaverman** [comment]
Again thanks for your help! :)

The situation has nothing to do with the license, but with the token used to download the segments. The situation is as follows:
- The client requests a token
- The client requests the manifest with the url: baseurl + token + channel + manifest.mpd
- The client parses the mpd and start downloading the segments with the url: baseurl + token + segmentnumber + .m4s
- After two minutes the client requests a new token
- The client starts downloading the segments with the url: baseurl + newtoken + segmentnumber + .m4s

So there is only a token refresh, no license request or manifest request. So my question is: is there a way to change the token in the segment request or do I need to request a new manifest with the newtoken, so that the segments will be downloaded with the new token?

**Comment by peak3d** [comment]
There is nothing like that implemented.

But there are 2 ways (same technique) you could use already now:

1.)
- The manifest URL points to your plugin (plugin::/yourplugin/manifest)
- Assuming that you have relative paths in mpd, this URL (your plugin) is called for manifest and segments
- You download the data and provide as response to this call.

2.) Same as 1.), but you spawn a socket listener in an service addon, manifest url is then the ip / port of this sevice.

I mislike the solution because you do not benefit from multithreading made in inputstream.adaptive (at least for solution 1)

What's the HTTP error number you receive if the token is expired?

**Comment by liberty-developer** [comment]
- inputstream.adaptive calls plugin://yourplugin/manifest (not sure how your addon is called)
maybe it could be also plugin://yourplugin/manifest_and_stream.py?action=manifest
- you build the real URL to retrieve the manifest, use socket / urllib or similiar to receive the data and return it.
Your plugin is a proxy, and the communication for manifest / streams is inputstream.adaptive <-> addon (proxy) <-> CDN instead of the current way inputstream.adaptive <-> CDN

Its just an idea, but you'll have much more work compared to if I made some changes.

Ites is that I call your addon to request new manifest URL (or stream headers (???) if 403 occurs

**Comment by peak3d** [comment]
- inputstream.adaptive calls plugin://yourplugin/manifest (not sure how your addon is called)
maybe it could be also plugin://yourplugin/manifest_and_stream.py?action=manifest
- you build the real URL to retrieve the manifest, use socket / urllib or similiar to receive the data and return it.
Your plugin is a proxy, and the communication for manifest / streams is inputstream.adaptive <-> addon (proxy) <-> CDN instead of the current way inputstream.adaptive <-> CDN

Its just an idea, but you'll have much more work compared to if I made some changes.

Ites is that I call your addon to request new manifest URL (or stream headers (???) if 403 occurs

**Comment by slaverman** [comment]
Ah I get it! That sounds like a lot of effort instead of just requesting a new manifest . What changes do you propose?

What do you mean with your last sentence? 'Ites is that I call your addon to request new manifest URL (or stream headers (???) if 403 occurs'

**Comment by peak3d** [comment]
Yes, I'll call your addon in case of 403 and you return  the updated parameters (=tokem in your case).

How is your token passed in the request? GET Parameter? or HTTP Header?

**Comment by slaverman** [comment]
The GET request is literally https://somestreamingprovider.com/vxtoken=abc123/56789808.m4s. It is in the middle of the URL, not as GET parameter after a questionmark.

So as I explained earlier the format is: baseurl + newtoken + segmentnumber + .m4s

**Comment by peak3d** [comment]
I'll come back to you with a solution

**Comment by slaverman** [comment]
Currently I got my addon running with a manifest refresh every two minutes, but have you looked at an alternative?

**Comment by peak3d** [comment]
I added some changes in a new branch mediarenewal, hopefully you can build the addon by yourself.

- pass a new property: 

inputstream.adaptive.media_renewal_url = "plugin://[your plugin id]?action=renew
^^ You can name parameters as you like, this is just an example

If inputstream.adaptive arrives HTTP 403, and you have passed the property, your addon will be called.
You have to return the new base-url (this is the manifest URL without the manifest file) in a listItem (path attribute will be used)

**Comment by slaverman** [comment]
So if I'm correct:

-  I set the property: inputstream.adaptive.media_renewal_url = "plugin://[myplugin]?action=renew
-  I create a function called 'renew' that handles the token refresh and returns the new base url with the token attached
- If inputstream.adaptive encounters a 403 error, the renew function is called and the new url will be used

Did I understand this correctly?

Is there an easy way to use inputstream.adaptive mediarenewal branch in Kodi?

Again, thank you so much for the great support! :)

**Comment by peak3d** [comment]
@slaverman your workflow is correct

> Is there an easy way to use inputstream.adaptive mediarenewal branch in Kodi?
Ok, understand, I'll prepare a test build

**Comment by peak3d** [comment]
Next try: http://jenkins.kodi.tv/job/WIN-64/5656/

**Comment by slaverman** [comment]
The 403 errors keep occuring, without recursively calling my addon. This is repeated in my log:
`ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403`

I saw that you looked for a 403 HTTP error and if the media_renewal_url_ is not empty.
`if (response.find("HTTP 403") != std::string::npos && !getMediaRenewalUrl().empty())`

Is the error really 'HTTP 403'? Because the log file states 'HTTP returned error 403'

**Comment by peak3d** [comment]
As you have already looked into code, you may have seen that I log the line out.
So -> simply look into kodi log to get your answer to this question.

**Comment by slaverman** [comment]
I saw in my log that it didn't reach the log line you meant. So I created a pull request where I moved the retry check. See https://github.com/peak3d/inputstream.adaptive/pull/166

**Comment by slaverman** [comment]
It still doesn't reach my log output. 
`18:21:54.488 T:1160   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403`
`18:21:54.488 T:1160   ERROR: CCurlFile::Open failed with code 403 for https://someprovider/somechannel;token=NWQxYTZlMjUw/video2/11737810.m4s:`
`18:21:54.488 T:1160   ERROR: AddOnLog: InputStream Adaptive: Download https://someprovider/somechannel;token=NWQxYTZlMjUw/video2/11737810.m4s doesn't provide any data: invalid`

I don't see any warnings where its says something in the format of:
`kodi::Log(ADDON_LOG_WARNING, "Download %s failed: %s", url, response.c_str());`

**Comment by peak3d** [comment]
Ok, better :-) What is your log saying?

**Comment by slaverman** [comment]
See https://pastebin.com/xe3Sq61w

The crashlog says 
`The thread tried to read from or write to a virtual address for which it does not have the appropriate access.`

**Comment by peak3d** [comment]
Ok, thx, need some more development in kodi to get the error code from a failed stream.

**Comment by slaverman** [comment]
All right, I will wait ;)

**Comment by peak3d** [comment]
@slaverman you can retry now with the latest nightly.

**Comment by slaverman** [comment]
Still crashing after:
`53:41.134 T:10036   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403`
`11:53:41.134 T:10036   ERROR: CCurlFile::Open failed with code 403 for https://someprovider/somechannel;token=MTAwZTk5NTYyNDFhNzA1ODkyZTEwZjI=/video2/11898963.m4s:
11:`

Sidenote: half the time Kodi encounters a 403 (when the token expires) and crashes, but now the other half of the time Kodi crashes after it encounters 404 not found (segment not available yet). Did you change something to the MPD processing that it now requests segments which are not available yet?

**Comment by peak3d** [comment]
can you provide a full kodi log pls?

**Comment by slaverman** [comment]
Sure! I disabled the component specific logging, because of the issue with CURL.
For the 403 --> https://pastebin.com/DQjtxXdx
For the 404 --> https://pastebin.com/YLEkbRhQ

**Comment by peak3d** [comment]
11:51:02.651 T:10776  NOTICE: ADDON: inputstream.adaptive v2.2.23 installed

This is NOT what I pushed yesterday night, are you sure that you use the nightly build last night?
I bumbed the version to 2.2.24.

**Comment by slaverman** [comment]
Good eye! But I have the latest nightly build installed (KodiSetup-20180626-0910789a-master-x64.exe). I will wait for the build for this night and give it a try tomorrow morning, thanks!

**Comment by peak3d** [comment]
Seems that last nights kodi build failed, because of that no new nightly.
http://jenkins.kodi.tv/job/WIN-64/5757/ is the build for your tests.

Regarding 404: The inputstream api has changed (in kodi) regarding if a stream is live or VOD.
I'll have to adapt this API change, thanks for reporting

**Comment by slaverman** [comment]
Thanks! My function to get a new base url is called when Kodi encounters a 403. But I still get the following error:
`AddOnLog: InputStream Adaptive: Retrieving renewal URL failed (plugin://plugin.video.ziggo/?action=refresh_token&username=test&token=jBhYWI0MasdaMWEzYzIwKAD)`

My code is roughly like this --> https://pastebin.com/riquyVgt

I added a print in the token_refresh to print the new url. So the new base url returned by new_base_url contains the new token, so that is not the problem.
`15:53:31.674 T:8440   DEBUG: https://someprovider.com/somechannel;token=jBhYWI0MzhjMWEzYzIwOWU`
It seems like inputstream.adaptive is not able to get the new base url to replace the old effective url

**Comment by peak3d** [comment]
You have to return a listItem element
