### ISSUE TITLE
[Dash] Location / Partial  Updates

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#804]
Finally found a service (Hulu live channes) that uses location.
It uses it with live streams so on a refresh, a smaller "update" manifest can be used.

When we find a location tag, that url should be used for the next refresh.
If that manifest has a location, we use that for the next... so on

Not sure behaviour of no location.
I assume just uses the last found.

It seems we are grabbing it here:
https://github.com/xbmc/inputstream.adaptive/blob/Nexus/src/parser/DASHTree.cpp#L1519

but then its never used:
https://github.com/xbmc/inputstream.adaptive/blob/Nexus/src/parser/DASHTree.cpp#L1675

After this is implemented, so would the need for partial updates.

**Comment by michaelarnauts** [comment]
I guess this is the same issue as https://github.com/xbmc/inputstream.adaptive/issues/286, but I couldn't reopen that issue and I made a workaround for it in VTM Go :)

**Comment by matthuisman** [comment]
@glennguy @CastagnaIT how much work would this involve?
The original hulu manifest stops working after 5mins and it each location url then has a new token on it
eg.
`<Location>https://livem-ftc-na.media.hulustream.com/v1/live/dash/continue/d34a8320-c6a3-4b44-a949-ab82e8edd357/manifest.mpd?cdns=sf&amp;cluster=blue&amp;origin=us-west-2&amp;duration=10800s&amp;manifest_cdn=fa&amp;repeat=true&amp;patch=true&amp;hpbsid_enabled=false&amp;uas_enabled=false&amp;segment_type_enabled=false&amp;query_params_v2=false&amp;unencrypted=false&amp;cver=0&amp;acquired_source_name=DEMN_ESPN2_EAST_MMA_CLT2-USW2&amp;stream_filter=fhd_high_surround&amp;prev_start=1688207707253&amp;prev_boundary_start=1688205304853&amp;prev_pts_values=AAC_1_CMAF_CENC_CTR%3D20917037056%7CEC3_1_CMAF_CENC_CTR%3D20917038535%7CH264_1_CMAF_CENC_CTR%3D26146296176&amp;token=1688208324_d98d485b117cb39a9080ab22d88d9e6520ba0cb0312bd9a51daa23a7e1c5afae</Location>`

I guess i could try do it in my proxy

**Comment by CastagnaIT** [comment]
Dash `Location` tag for updates should be already fixed on last Omega nightly

**Comment by matthuisman** [comment]
@CastagnaIT thanks. was that part of this PR https://github.com/xbmc/inputstream.adaptive/pull/1288 ?

**Comment by matthuisman** [comment]
@dapharsyde are you able to test with latest Omega IA nightly build?

**Comment by CastagnaIT** [comment]
i dont remember exactly its possible has been fixed with the big parsers rework

you can find some builds here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Omega/79/artifacts/

**Comment by dapharsyde** [comment]
I can confirm the HTTP 410 errors reported in [this issue](https://github.com/matthuisman/slyguy.addons/issues/488) are fixed with a nightly build of IA for Omega.  Is it possible this will be backported to a Nexus release, or should I start planning to upgrade my main systems to Omega to benefit from this fix?

**Comment by CastagnaIT** [comment]
thanks for the confirm, it should be a minor fix to do i will let you know

**Comment by CastagnaIT** [comment]
@dapharsyde there when you can try test on Nexus with this test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1314/1/artifacts

**Comment by dapharsyde** [comment]
Update: I may have installed the wrong version of the plugin.  See my new comment below with actual test results.  Sorry for the confusion.

~~I tested in Nexus with the build of IA provided above, and the HTTP 410 errors are still occurring - so I guess that means there was some other fix that still needs to be backported?~~

~~Attached are the log file and manifests.~~

~~[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/11962149/kodi.log)~~

~~[manifests.zip](https://github.com/xbmc/inputstream.adaptive/files/11962147/manifests.zip)~~

**Comment by matthuisman** [comment]
from the log, I can see it is still trying to use dash/initial/ 
So looks like its not following the Location tag

**Comment by dapharsyde** [comment]
Hmm, strange.  There's a small chance I installed the wrong version of the IA plugin for that previous test.  I just reinstalled the plugin, restarted kodi, and tested again.  I noticed the logfile now shows dash/continue instead of dash/initial, but the stream now stops within < 30 seconds, with the log file showing this warning "warning <general>: AddOnLog: inputstream.adaptive: No periods in the manifest"

attached are the log file and manifest files:

[manifests.zip](https://github.com/xbmc/inputstream.adaptive/files/11963330/manifests.zip)

[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/11963331/kodi.log)

**Comment by matthuisman** [comment]
yeh, this is partial manifest updates - i suspect Nexus code wont support those very well. Castagna will be able to confirm.
It may be too big change to bring back support for that

**Comment by matthuisman** [comment]
I think this issue could be marked as FIXED though with his latest change.
Location and partial works

**Comment by dapharsyde** [comment]
> I think this issue could be marked as FIXED though with his latest change. Location and partial works

But only in Omega, not in Nexus (and likely not anytime soon), right?  Sorry, trying to follow along the best I can :)

Also, although the nightly Omega IA build gets around the HTTP 410 errors, it now has [issues](https://github.com/xbmc/inputstream.adaptive/issues/1290#issuecomment-1621453390), seemingly when switching between advertisements and regular content.

**Comment by CastagnaIT** [comment]
worth a try, i hoped but as i was supecting there are other problems under the hood...
that are linked to the recents new reworks to manifest live updates that fixed different use cases

should be PR 1302 but this require old rework PR to be included
since we cannot backport changes that include features or breaking changes
is quite a big job make a kind of backport bypassing these changes
you need to rewrite code different way its quite big job not worth to me

i will close this Issue since its fixed on Omega
